
@HOST_NAME = https://learning-lantern.herokuapp.com

### Create
POST {{HOST_NAME}}/api/Auth/Create HTTP/1.1
Content-Type: application/json

{
    "Email": "ahmmohfat18@compit.aun.edu.eg",
    "Password": "Fathy@123",
    "FirstName": "Ahmed",
    "LastName": "Fathy"
}

### SignIn
POST {{HOST_NAME}}/api/Auth/SignIn HTTP/1.1
Content-Type: application/json

{
    "Email": "ahmmohfat18@compit.aun.edu.eg",
    "Password": "Fathy@123"
}

### FindById
GET {{HOST_NAME}}/api/User?userId=xxx
Authorization: Bearer xxx

### Update
PUT {{HOST_NAME}}/api/User/Update HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx

{
  "id": "xxx",
  "email": "ahmmohfat18@compit.aun.edu.eg",
  "firstName": "Ahmed",
  "lastName": "Osman"
}

### Delete
DELETE {{HOST_NAME}}/api/User/Delete?userId=xxx HTTP/1.1
Authorization: Bearer xxx