
@HOST_NAME = https://learning-lantern.herokuapp.com

### Auth/Create
POST {{HOST_NAME}}/api/Auth/Create HTTP/1.1
Content-Type: application/json

{
    "University": "Assiut University",
    "FirstName": "Test",
    "LastName": "Mail",
    "Email": "test@gmail.com",
    "Password": "Pa$$w0rd"
}

### /Auth/ConfirmEmail
GET {{HOST_NAME}}/api/Auth/ConfirmEmail?userId=xxx&token=xxx

### Auth/SignIn
POST {{HOST_NAME}}/api/Auth/SignIn HTTP/1.1
Content-Type: application/json

{
    "University": "Assiut University",
    "Email": "test@gmail.com",
    "Password": "Pa$$w0rd"
}

### User/FindById
GET {{HOST_NAME}}/api/User?userId=xxx HTTP/1.1
Authorization: Bearer xxx

### User/Update
PUT {{HOST_NAME}}/api/User/Update HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx

{
    "Id": "xxx",
    "University": "Cairo University",
    "FirstName": "Test",
    "LastName": "App",
    "Email": "test@gmail.com"
}

### User/Delete
DELETE {{HOST_NAME}}/api/User/Delete?userId=xxx HTTP/1.1
Authorization: Bearer xxx
