
@HOST_NAME = https://localhost:5001

### SignUp
POST https://localhost:5001/api/User/SignUp HTTP/1.1
Content-Type: application/json

{
    "Email": "ahmed.fathy.dev@gmail.com",
    "Password": "Fathy123",
    "FirstName": "Ahmed",
    "LastName": "Fathy"
}