
@HOST_NAME = https://localhost:5001

### User/FindById
GET {{HOST_NAME}}/api/User?userId=xxx HTTP/1.1
Authorization: Bearer xxx

### User/Update
PUT {{HOST_NAME}}/api/User/Update HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx

{
    "Id": "xxx",
    "University": "Assiut University",
    "FirstName": "Test",
    "LastName": "User",
    "Email": "user@example.com"
}

### User/Delete
DELETE {{HOST_NAME}}/api/User/Delete?userId=xxx HTTP/1.1
Authorization: Bearer xxx
